# Generated by Django 4.1.4 on 2022-12-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('CLIENT', 'client'), ('EMPLOYEE', 'employee')], default='CLIENT', max_length=8)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='ProfileEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Ваша фотография с собакой')),
                ('content', models.TextField(verbose_name='Опишите себя')),
                ('achievements', models.TextField(verbose_name='Ваши достижения|необязательно')),
            ],
            options={
                'verbose_name': 'Профиль Сотрудника',
                'verbose_name_plural': 'Профиль Сотрудника',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('Ответственный', 'Ответственный'), ('Пунктуальный', 'Пунктуальный'), ('Стрессоустойчивый', 'Стрессоустойчивый'), ('Внимательный', 'Внимательный'), ('Терпеливый', 'Терпеливый'), ('Доброта', 'Доброта'), ('Честность', 'Честность'), ('Отзывчивость', 'Отзывчивость')], default='Выберите', max_length=17, verbose_name='Навыки')),
                ('profileemployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='users.profileemployee', verbose_name='Профиль Сотрудника')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_schedule', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default=('Понедельник', 'Понедельник'), max_length=100, unique=True, verbose_name='График недели')),
                ('time', models.CharField(choices=[('с 07:00 утра до 22:00', 'с 07:00 утра до 22:00'), ('с 09:00 утра до 21:00', 'с 09:00 утра до 21:00'), ('с 12:00 до 21:00', 'с 12:00 до 21:00')], default=(1, 'с 07:00 утра до 22:00'), max_length=100, verbose_name='Время')),
                ('profileemployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_schedule', to='users.profileemployee', verbose_name='Профиль Сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.useraccount',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.useraccount',),
        ),
        migrations.AddField(
            model_name='profileemployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(max_length=100, verbose_name='Порода')),
                ('content', models.TextField(verbose_name='Опишите вашу собаку')),
                ('name_dog', models.CharField(max_length=100, verbose_name='Имя собаки')),
                ('image', models.ImageField(upload_to='', verbose_name='Ваша фотография')),
                ('image_dog', models.ImageField(upload_to='', verbose_name='Фотография вашей собаки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент')),
            ],
        ),
    ]
