# Generated by Django 4.1.4 on 2022-12-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема|')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание|')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка|')),
            ],
        ),
    ]
